CREATE TABLE `balancesheet_outcome_2025` (
  `balancesheet_outcome_id` bigint NOT NULL AUTO_INCREMENT COMMENT '政治資金収支報告書主出項目Id',
  `balancesheet_outcome_code` bigint DEFAULT NULL COMMENT '政治資金収支報告書支出項目同一識別コード',
  `saishin_kbn` int DEFAULT NULL COMMENT '最新区分',
  `political_organization_id` bigint DEFAULT NULL COMMENT '政治資金団体Id',
  `political_organization_code` int DEFAULT NULL COMMENT '政治資金団体同一識別コード',
  `political_organization_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '政治資金団体名称',
  `shoshou_id` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '書証Id',
  `shoshou_history_code` bigint DEFAULT NULL COMMENT '書証識別コード',
  `shoshou_kbn` int DEFAULT NULL COMMENT '書証区分',
  `reading_line` int DEFAULT NULL COMMENT '書証読み取り行',
  `refer_digest` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '参照した摘要',
  `amount` bigint DEFAULT NULL COMMENT '取引金額',
  `accrual_date` date DEFAULT NULL COMMENT '発生日',
  `is_edit_auto_input` bit(1) DEFAULT NULL,
  `report_kbn` int DEFAULT NULL COMMENT '収支報告区分',
  `youshiki_kbn` int DEFAULT NULL COMMENT '様式仕訳区分',
  `youshiki_eda_kbn` int DEFAULT NULL COMMENT '様式仕訳枝項目区分',
  `categorize_group` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '支出大項目',
  `item_name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '項目名称',
  `item_id_kbn` int DEFAULT NULL COMMENT '項目名称Id区分',
  `general_item_id` bigint DEFAULT NULL COMMENT '一般項目名称Id',
  `general_item_code` int DEFAULT NULL COMMENT '一般名称同一識別コード',
  `continue_buissiness_id` bigint DEFAULT NULL COMMENT '継続事業Id',
  `continue_buissiness_code` int DEFAULT NULL COMMENT '継続事業同一識別コード',
  `relation_kbn` int DEFAULT NULL COMMENT '関連者区分',
  `relation_person_id` bigint DEFAULT NULL COMMENT '関連者個人Id',
  `relation_person_code` int DEFAULT NULL COMMENT '関連者個人同一識別コード',
  `relation_corporation_id` bigint DEFAULT NULL COMMENT '関連者法人Id',
  `relation_corporation_code` int DEFAULT NULL COMMENT '関連者法人同一識別コード',
  `relation_politics_organization_id` bigint DEFAULT NULL COMMENT '関連者政治団体Id',
  `relation_politics_organization_code` int DEFAULT NULL COMMENT '関連者政治団体同一識別コード',
  `orgnization_address` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '個人・団体住所',
  `profession_orgnization_name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '団体代表者・職業',
  `biko` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '備考',
  `is_expenditures_related_grants` tinyint(1) DEFAULT NULL COMMENT '交付金に係る支出',
  `not_collect_recipt_kbn` bit(1) DEFAULT NULL,
  `note` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '意見付記',
  `is_differ_precedent` tinyint(1) DEFAULT NULL COMMENT '前例と異なる処理フラグ',
  `storaged_document_id_list` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '保全証票リスト',
  `login_user_id` bigint DEFAULT NULL COMMENT 'ログインユーザId',
  `login_user_code` int DEFAULT NULL COMMENT 'ログインユーザ同一識別コード',
  `login_user_name` varchar(150) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'ログインユーザ名',
  `update_time` timestamp NULL DEFAULT NULL COMMENT '更新時間',
  PRIMARY KEY (`balancesheet_outcome_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
