CREATE TABLE `political_organization` (
  `political_organization_id` bigint NOT NULL AUTO_INCREMENT COMMENT '政治団体Id',
  `political_organization_code` int DEFAULT NULL,
  `political_organization_name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '政治団体名称',
  `saishin_kbn` int DEFAULT NULL COMMENT '最新区分',
  `delegate_id` bigint DEFAULT NULL COMMENT '代表者Id',
  `delegate_code` int DEFAULT NULL COMMENT '代表者同一識別コード',
  `delegate_name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '代表者姓名',
  `account_officer_id` bigint DEFAULT NULL COMMENT '会計責任者Id',
  `account_officer_code` int DEFAULT NULL COMMENT '会計責任者同一識別コード',
  `account_officer_name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '会計責任者名称',
  `account_staff1_id` bigint DEFAULT NULL COMMENT '事務担当者1Id',
  `account_staff1_code` int DEFAULT NULL COMMENT '事務担当者1同一識別コード',
  `account_staff1_name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '事務担当者1名称',
  `account_staff2_id` bigint DEFAULT NULL COMMENT '事務担当者2Id',
  `account_staff2_code` int DEFAULT NULL COMMENT '事務担当者2同一識別コード',
  `account_staff2_name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '事務担当者2名称',
  `account_staff3_id` bigint DEFAULT NULL COMMENT '事務担当者3Id',
  `account_staff3_code` int DEFAULT NULL COMMENT '事務担当者3同一識別コード',
  `account_staff3_name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '事務担当者3名称',
  `table_all_search_text` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'テーブル全文検索カラム',
  `insert_user_id` bigint DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザ同一識別コード',
  `insert_user_name` varchar(300) DEFAULT NULL COMMENT '挿入ユーザ姓名',
  `insert_timestamp` datetime NULL DEFAULT NULL COMMENT '挿入タイムスタンプ',
  `update_user_id` bigint DEFAULT NULL COMMENT '更新ユーザId',
  `update_user_code` int DEFAULT NULL COMMENT '更新ユーザ同一識別コード',
  `update_user_name` varchar(300) DEFAULT NULL COMMENT '更新ユーザ姓名',
  `update_timestamp` datetime NULL DEFAULT NULL COMMENT '更新タイムスタンプ',
  `account_staff1code` int DEFAULT NULL,
  `account_staff1id` bigint DEFAULT NULL,
  `account_staff1name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `account_staff2code` int DEFAULT NULL,
  `account_staff2id` bigint DEFAULT NULL,
  `account_staff2name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `account_staff3code` int DEFAULT NULL,
  `account_staff3id` bigint DEFAULT NULL,
  `account_staff3name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`political_organization_id`),
  FULLTEXT KEY `table_all_search_text` (`table_all_search_text`) /*!50100 WITH PARSER `ngram` */ 
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
