CREATE TABLE `propose_csv_read_template` (
  `propose_csv_read_template_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'CSV読取り仕様Id',
  `propose_csv_read_template_code` int DEFAULT NULL COMMENT 'CSV読取り仕様同一識別コード',
  `propose_csv_read_template_name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'CSV読取り仕様名称',
  `saishin_kbn` int DEFAULT NULL COMMENT '最新区分',
  `financial_org_kbn` int DEFAULT NULL COMMENT '金融機関区分',
  `financial_org_id` bigint DEFAULT NULL COMMENT '金融機関Id',
  `financial_org_code` int DEFAULT NULL COMMENT '金融機関同一識別コード',
  `financial_org_name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '金融機関名称',
  `has_header` bit(1) DEFAULT NULL COMMENT 'データヘッダ有無',
  `array_number` int DEFAULT NULL COMMENT '配列桁数',
  `array_text` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '指定配列内容',
  `edit_id` bigint DEFAULT NULL COMMENT '編集中読み取り仕様Id',
  `in_prosessing` tinyint(1) DEFAULT NULL COMMENT '申請継続中該否',
  `is_accepted` tinyint(1) DEFAULT NULL COMMENT '申請承認該否',
  `judge_reason` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '判定理由',
  `shoshou_id` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '書証Id',
  `shoshou_code` bigint DEFAULT NULL COMMENT '書証同一識別コード',
  `shoshou_kbn` int DEFAULT NULL COMMENT '書証区分',
  `table_all_search_text` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'テーブル全文検索カラム',
  `insert_user_id` bigint DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザ同一識別コード',
  `insert_user_name` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '挿入ユーザ姓名',
  `insert_timestamp` timestamp NULL DEFAULT NULL COMMENT '挿入タイムスタンプ',
  `update_user_id` bigint DEFAULT NULL COMMENT '更新ユーザId',
  `update_user_code` int DEFAULT NULL COMMENT '更新ユーザ同一識別コード',
  `update_user_name` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '更新ユーザ姓名',
  `update_timestamp` timestamp NULL DEFAULT NULL COMMENT '更新タイムスタンプ',
  PRIMARY KEY (`propose_csv_read_template_id`),
  FULLTEXT KEY `table_all_search_text` (`table_all_search_text`) /*!50100 WITH PARSER `ngram` */ 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
