CREATE TABLE `send_alert_sns_message_2025` (
  `send_alert_sns_message_id` bigint NOT NULL AUTO_INCREMENT COMMENT '項目名称取得Id',
  `send_alert_sns_message_code` int DEFAULT NULL COMMENT '項目名称取得同一識別コード',
  `saishin_kbn` int DEFAULT NULL COMMENT '最新区分',
  `send_user_id` bigint DEFAULT NULL COMMENT '送信先ユーザId',
  `send_user_code` int DEFAULT NULL COMMENT '送信先ユーザ同一識別コード',
  `send_user_name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '送信先ユーザ名称',
  `send_datetime` datetime DEFAULT NULL COMMENT '次回送信時刻',
  `sns_logic_id` int DEFAULT NULL COMMENT '送信SNSロジックId',
  `times_retry_next` int DEFAULT NULL COMMENT '次回送信試行回目',
  `datetime_times1` datetime DEFAULT NULL COMMENT '再試行1回目時間(3時間後)',
  `datetime_times2` datetime DEFAULT NULL COMMENT '再試行1回目時間(6時間後)',
  `datetime_times3` datetime DEFAULT NULL COMMENT '再試行1回目時間(12時間後)',
  `datetime_times4` datetime DEFAULT NULL COMMENT '再試行1回目時間(24時間後)',
  `datetime_times5` datetime DEFAULT NULL COMMENT '再試行1回目時間(48時間後)',
  `body_text` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'メッセージ本文',
  `insert_user_id` bigint DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザ同一識別コード',
  `insert_user_name` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '挿入ユーザ姓名',
  `insert_timestamp` datetime DEFAULT NULL COMMENT '挿入タイムスタンプ',
  `update_user_id` bigint DEFAULT NULL COMMENT '更新ユーザId',
  `update_user_code` int DEFAULT NULL COMMENT '更新ユーザ同一識別コード',
  `update_user_name` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '更新ユーザ姓名',
  `update_timestamp` datetime DEFAULT NULL COMMENT '更新タイムスタンプ',
  PRIMARY KEY (`send_alert_sns_message_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3784 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
